CREATE TYPE "PriceDerivationType" AS ENUM ('COST_MULTIPLIER', 'TIER_PERCENTAGE');
ALTER TABLE "Company" ADD COLUMN "priceTierId" TEXT, ADD COLUMN "workingDays" JSONB NOT NULL DEFAULT '[1,2,3,4,5]';
ALTER TABLE "MenuCategory" ADD COLUMN "secret" BOOLEAN NOT NULL DEFAULT false;
CREATE TABLE "PriceTier" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"isDefault" BOOLEAN NOT NULL DEFAULT false,"isActive" BOOLEAN NOT NULL DEFAULT true,"derivationType" "PriceDerivationType","costMultiplier" DECIMAL(12,6),"sourceTierId" TEXT,"percentage" DECIMAL(12,6),CONSTRAINT "PriceTier_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DishPrice" ("id" TEXT NOT NULL,"dishId" TEXT NOT NULL,"tierId" TEXT NOT NULL,"price" DECIMAL(12,2) NOT NULL,CONSTRAINT "DishPrice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OptionPrice" ("id" TEXT NOT NULL,"optionId" TEXT NOT NULL,"tierId" TEXT NOT NULL,"price" DECIMAL(12,2) NOT NULL,CONSTRAINT "OptionPrice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CompanyHiddenCategory" ("companyId" TEXT NOT NULL,"categoryId" TEXT NOT NULL,CONSTRAINT "CompanyHiddenCategory_pkey" PRIMARY KEY ("companyId","categoryId"));
CREATE TABLE "CompanyHiddenDish" ("companyId" TEXT NOT NULL,"dishId" TEXT NOT NULL,CONSTRAINT "CompanyHiddenDish_pkey" PRIMARY KEY ("companyId","dishId"));
CREATE TABLE "CompanyHoliday" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"date" DATE NOT NULL,"label" TEXT,CONSTRAINT "CompanyHoliday_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PriceTier_name_key" ON "PriceTier"("name");
CREATE UNIQUE INDEX "DishPrice_dishId_tierId_key" ON "DishPrice"("dishId","tierId");
CREATE UNIQUE INDEX "OptionPrice_optionId_tierId_key" ON "OptionPrice"("optionId","tierId");
CREATE UNIQUE INDEX "CompanyHoliday_companyId_date_key" ON "CompanyHoliday"("companyId","date");
ALTER TABLE "Company" ADD CONSTRAINT "Company_priceTierId_fkey" FOREIGN KEY ("priceTierId") REFERENCES "PriceTier"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PriceTier" ADD CONSTRAINT "PriceTier_sourceTierId_fkey" FOREIGN KEY ("sourceTierId") REFERENCES "PriceTier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DishPrice" ADD CONSTRAINT "DishPrice_dishId_fkey" FOREIGN KEY ("dishId") REFERENCES "Dish"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DishPrice" ADD CONSTRAINT "DishPrice_tierId_fkey" FOREIGN KEY ("tierId") REFERENCES "PriceTier"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OptionPrice" ADD CONSTRAINT "OptionPrice_optionId_fkey" FOREIGN KEY ("optionId") REFERENCES "Option"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OptionPrice" ADD CONSTRAINT "OptionPrice_tierId_fkey" FOREIGN KEY ("tierId") REFERENCES "PriceTier"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CompanyHiddenCategory" ADD CONSTRAINT "CompanyHiddenCategory_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CompanyHiddenCategory" ADD CONSTRAINT "CompanyHiddenCategory_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "MenuCategory"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CompanyHiddenDish" ADD CONSTRAINT "CompanyHiddenDish_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CompanyHiddenDish" ADD CONSTRAINT "CompanyHiddenDish_dishId_fkey" FOREIGN KEY ("dishId") REFERENCES "Dish"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CompanyHoliday" ADD CONSTRAINT "CompanyHoliday_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
